name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Cambia "main" si tu rama principal tiene otro nombre.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # La carpeta raíz donde están tus archivos estáticos.
